---
title: "MarcelPitching2019"
output: html_document
date: "2024-07-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Load data/packages

library(tidyverse)
library(baseballr)
library(plyr)
library(dplyr)
library(remotes)
library(expss)
library(metR)
library(mgcv)
library(gridExtra)
library(ggimage)
library(xgboost)
library(flextable)
library(formattable)
library(astroFns)
library(grid)
library(tibble)
library(RODBC)
library(odbc)
library(sqldf)
```

```{r}
db_intern_connection <- odbcDriverConnect(paste('driver={SQL Server};server=OPSDBOAK85',
                                            Sys.getenv("SERVER"),
                                            ';database=mlb_stats',
                                            Sys.getenv("DATABASE"),
                                            ';trusted_connection=true', sep = ""))
```

```{r}
pitchingstatsquery2016 <- "
SELECT [Name]
      ,[PlayerID]
      ,[TeamID]
      ,[TeamName]
      ,[TeamAbbr]
      ,[SportCode]
      ,[Org]
      ,[LeagueLevel]
      ,[League]
      ,[Season]
      ,[Age]
      ,[GameType]
      ,[G]
      ,[GS]
      ,[W]
      ,[L]
      ,[SV]
      ,[IP_Outs]
      ,[IP]
      ,[ERA]
      ,[PA]
      ,[AB]
      ,[H]
      ,[B1]
      ,[B2]
      ,[B3]
      ,[HR]
      ,[R]
      ,[ER]
      ,[BB]
      ,[SO]
      ,[AVG]
      ,[OBP]
      ,[SLG]
      ,[BABIP]
      ,[wOBA]
      ,[wAVG]
      ,[TB]
      ,[GDP]
      ,[HBP]
      ,[SH]
      ,[SF]
      ,[IBB]
      ,[TP]
      ,[WP]
      ,[BIP]
      ,[GB]
      ,[LD]
      ,[FB]
      ,[PU]
      ,[IFFB]
      ,[wRC]
      ,[wRAA]
      ,[InheritedRunners]
      ,[InheritedRunScored]
      ,[QS]
      ,[GF]
      ,[FIPAdj]
      ,[FIPAdjMinus]
      ,[FirstGame]
      ,[LastGame]
      ,[UpdatedDate]
  FROM [mlb_stats].[dbo].[stat_pitcher_basic]
  WHERE LeagueLevel = 1 AND GameType = 'R' AND PA > 100 AND Season = 2016
"

pitchingstats2016 <- sqlQuery(db_intern_connection, pitchingstatsquery2016)

print(pitchingstats2016)
```


```{r}
pitchingstatsquery2017 <- "
SELECT [Name]
      ,[PlayerID]
      ,[TeamID]
      ,[TeamName]
      ,[TeamAbbr]
      ,[SportCode]
      ,[Org]
      ,[LeagueLevel]
      ,[League]
      ,[Season]
      ,[Age]
      ,[GameType]
      ,[G]
      ,[GS]
      ,[W]
      ,[L]
      ,[SV]
      ,[IP_Outs]
      ,[IP]
      ,[ERA]
      ,[PA]
      ,[AB]
      ,[H]
      ,[B1]
      ,[B2]
      ,[B3]
      ,[HR]
      ,[R]
      ,[ER]
      ,[BB]
      ,[SO]
      ,[AVG]
      ,[OBP]
      ,[SLG]
      ,[BABIP]
      ,[wOBA]
      ,[wAVG]
      ,[TB]
      ,[GDP]
      ,[HBP]
      ,[SH]
      ,[SF]
      ,[IBB]
      ,[TP]
      ,[WP]
      ,[BIP]
      ,[GB]
      ,[LD]
      ,[FB]
      ,[PU]
      ,[IFFB]
      ,[wRC]
      ,[wRAA]
      ,[InheritedRunners]
      ,[InheritedRunScored]
      ,[QS]
      ,[GF]
      ,[FIPAdj]
      ,[FIPAdjMinus]
      ,[FirstGame]
      ,[LastGame]
      ,[UpdatedDate]
  FROM [mlb_stats].[dbo].[stat_pitcher_basic]
  WHERE LeagueLevel = 1 AND GameType = 'R' AND PA > 100 AND Season = 2017
"

pitchingstats2017 <- sqlQuery(db_intern_connection, pitchingstatsquery2017)

print(pitchingstats2017)
```
```{r}
pitchingstatsquery2018 <- "
SELECT [Name]
      ,[PlayerID]
      ,[TeamID]
      ,[TeamName]
      ,[TeamAbbr]
      ,[SportCode]
      ,[Org]
      ,[LeagueLevel]
      ,[League]
      ,[Season]
      ,[Age]
      ,[GameType]
      ,[G]
      ,[GS]
      ,[W]
      ,[L]
      ,[SV]
      ,[IP_Outs]
      ,[IP]
      ,[ERA]
      ,[PA]
      ,[AB]
      ,[H]
      ,[B1]
      ,[B2]
      ,[B3]
      ,[HR]
      ,[R]
      ,[ER]
      ,[BB]
      ,[SO]
      ,[AVG]
      ,[OBP]
      ,[SLG]
      ,[BABIP]
      ,[wOBA]
      ,[wAVG]
      ,[TB]
      ,[GDP]
      ,[HBP]
      ,[SH]
      ,[SF]
      ,[IBB]
      ,[TP]
      ,[WP]
      ,[BIP]
      ,[GB]
      ,[LD]
      ,[FB]
      ,[PU]
      ,[IFFB]
      ,[wRC]
      ,[wRAA]
      ,[InheritedRunners]
      ,[InheritedRunScored]
      ,[QS]
      ,[GF]
      ,[FIPAdj]
      ,[FIPAdjMinus]
      ,[FirstGame]
      ,[LastGame]
      ,[UpdatedDate]
  FROM [mlb_stats].[dbo].[stat_pitcher_basic]
  WHERE LeagueLevel = 1 AND GameType = 'R' AND PA > 100 AND Season = 2018
"

pitchingstats2018 <- sqlQuery(db_intern_connection, pitchingstatsquery2018)

print(pitchingstats2018)
```


```{r}
pitchingstatsquery2019 <- "
SELECT [Name]
      ,[PlayerID]
      ,[TeamID]
      ,[TeamName]
      ,[TeamAbbr]
      ,[SportCode]
      ,[Org]
      ,[LeagueLevel]
      ,[League]
      ,[Season]
      ,[Age]
      ,[GameType]
      ,[G]
      ,[GS]
      ,[W]
      ,[L]
      ,[SV]
      ,[IP_Outs]
      ,[IP]
      ,[ERA]
      ,[PA]
      ,[AB]
      ,[H]
      ,[B1]
      ,[B2]
      ,[B3]
      ,[HR]
      ,[R]
      ,[ER]
      ,[BB]
      ,[SO]
      ,[AVG]
      ,[OBP]
      ,[SLG]
      ,[BABIP]
      ,[wOBA]
      ,[wAVG]
      ,[TB]
      ,[GDP]
      ,[HBP]
      ,[SH]
      ,[SF]
      ,[IBB]
      ,[TP]
      ,[WP]
      ,[BIP]
      ,[GB]
      ,[LD]
      ,[FB]
      ,[PU]
      ,[IFFB]
      ,[wRC]
      ,[wRAA]
      ,[InheritedRunners]
      ,[InheritedRunScored]
      ,[QS]
      ,[GF]
      ,[FIPAdj]
      ,[FIPAdjMinus]
      ,[FirstGame]
      ,[LastGame]
      ,[UpdatedDate]
  FROM [mlb_stats].[dbo].[stat_pitcher_basic]
  WHERE LeagueLevel = 1 AND GameType = 'R' AND PA > 100 AND Season = 2019
"

pitchingstats2019 <- sqlQuery(db_intern_connection, pitchingstatsquery2019)

print(pitchingstats2019)
```


```{r}
colstoselect <- c("Name", "PlayerID", "Season", "Age", "ERA", "IP", "PA", "BB", "SO", "AVG", "SLG", "OBP", "wRAA", "FIPAdjMinus")

pitchingstats2016_selected <- pitchingstats2016[, colstoselect]
pitchingstats2017_selected <- pitchingstats2017[, colstoselect]
pitchingstats2018_selected <- pitchingstats2018[, colstoselect]
pitchingstats2019_selected <- pitchingstats2019[, colstoselect]
```

```{r}
pitchingstats2016_selected <- pitchingstats2016_selected %>%
  mutate(BBRate = BB/ PA) %>%
  mutate(SORate = SO/ PA) 
pitchingstats2017_selected <- pitchingstats2017_selected %>%
  mutate(BBRate = BB/ PA) %>%
  mutate(SORate = SO/ PA)
pitchingstats2018_selected <- pitchingstats2018_selected %>%
  mutate(BBRate = BB/ PA) %>%
  mutate(SORate = SO/ PA)

pitchingstats2019_selected <- pitchingstats2019_selected %>%
  mutate(BBRate = BB/ PA) %>%
  mutate(SORate = SO/ PA)
```

```{r}
numeric_columns <- c("IP", "PA", "ERA", "AVG","OBP", "SLG", "wRAA", "BBRate", "SORate", "FIPAdjMinus")

pitching_stats_2018_weighted <- pitchingstats2018_selected[, numeric_columns] * 5
pitching_stats_2017_weighted <- pitchingstats2017_selected[, numeric_columns] * 4
pitching_stats_2016_weighted <- pitchingstats2016_selected[, numeric_columns] * 3
```

```{r}
pitching_stats_2016_weighted <- cbind(pitchingstats2016_selected[, setdiff(names(pitchingstats2016_selected), numeric_columns)], pitching_stats_2016_weighted)
pitching_stats_2017_weighted <- cbind(pitchingstats2017_selected[, setdiff(names(pitchingstats2017_selected), numeric_columns)], pitching_stats_2017_weighted)
pitching_stats_2018_weighted <- cbind(pitchingstats2018_selected[, setdiff(names(pitchingstats2018_selected), numeric_columns)], pitching_stats_2018_weighted)
```


```{r}
combined_stats <- left_join(pitching_stats_2016_weighted, pitching_stats_2017_weighted, by = "PlayerID", suffix = c("_2016", "_2017"))

combined_stats <- left_join(combined_stats, pitching_stats_2018_weighted, by = "PlayerID", suffix = c("", "_2018"))
combined_stats_filter <- combined_stats %>%
  filter(!is.na(PA_2016) & !is.na(PA_2017) & !is.na(PA))
combined_stats_unique <- combined_stats_filter %>%
  distinct(Name, .keep_all = TRUE)
```
```{r}
combined_stats_weighted <- combined_stats_unique %>%
  mutate(weighted_IP = (IP_2016 + IP_2017 + IP) / 12) %>%
  mutate(weighted_PA = (PA_2016 + PA_2017 + PA) / 12) %>%
  mutate(weighted_BBRate = (BBRate_2016 + BBRate_2017 + BBRate) / 12) %>%
  mutate(weighted_SORate = (SORate_2016 + SORate_2017 + SORate) / 12) %>%
  mutate(weighted_ERA = (ERA_2016 + ERA_2017 + ERA) / 12) %>%
  mutate(weighted_AVG = (AVG_2016 + AVG_2017 + AVG) / 12) %>%
  mutate(weighted_SLG = (SLG_2016 + SLG_2017 + SLG) / 12) %>%
  mutate(weighted_OBP = (OBP_2016 + OBP_2017 + OBP) / 12) %>%
  mutate(weighted_FIPAdjMinus = (FIPAdjMinus_2016 + FIPAdjMinus_2017 + FIPAdjMinus) / 12)
#%>%
 # mutate(weighted_wRAA = (wRAA_2016 + wRAA_2017 + wRAA) / 12)
```

```{r}
weighted_stats <- combined_stats_weighted %>%
  select(Name, PlayerID,weighted_IP,weighted_PA, weighted_BBRate, weighted_SORate, weighted_ERA, weighted_AVG, weighted_SLG, weighted_OBP,weighted_OBP, weighted_FIPAdjMinus
      #   ,weighted_wRAA
         ) %>%
  filter(weighted_PA >= 150)
```

```{r}
merged_stats_w_2019 <- left_join(pitchingstats2019_selected, weighted_stats, by = c("PlayerID", "Name"))
merged_stats_w_2019 <- merged_stats_w_2019 %>%
  filter(!is.na(weighted_PA))
```

```{r}
age_adjustment <- function(age) {
  ifelse(is.na(age), 1,
    ifelse(age <= 0, 1,
      ifelse(age > 29, 1 / (1 + 0.003 * (age - 29)),
        1 + 0.015 * (29 - age)
      )
    )
  )
}
```

```{r}
age_adjustment_reciprocal <- function(age) {
  ifelse(is.na(age), 1,
    ifelse(age <= 0, 1,
  ifelse (age > 29, 1 + 0.003 * (age-29),
    1/(1 + 0.015 * (29-age)
    )
  )
    )
  )
}
```


```{r}
merged_stats_w_2019 <- merged_stats_w_2019 %>%
  mutate(age_adjustment_factor = age_adjustment(Age),
         age_reciprocal = age_adjustment_reciprocal(Age)) %>%
  filter(PA>=150)
```

```{r}
age_adj_stats_w_2019 <- merged_stats_w_2019 %>%
  mutate(proj_AVG = weighted_AVG * age_adjustment_reciprocal(Age)) %>%
  mutate(proj_OBP = weighted_OBP * age_adjustment_reciprocal(Age)) %>%
  mutate(proj_SLG = weighted_SLG * age_adjustment_reciprocal(Age)) %>%
  mutate(proj_BBRate = weighted_BBRate * age_adjustment_reciprocal(Age)) %>%
  mutate(proj_SORate = weighted_SORate * age_adjustment(Age)) %>%
  mutate(proj_FIPAdjMinus = weighted_FIPAdjMinus * age_adjustment_reciprocal(Age)) %>%
  mutate(proj_ERA = weighted_ERA * age_adjustment_reciprocal(Age))  
 # mutate(proj_wRAA = weighted_wRAA * (2-age_adjustment(Age)))
```

```{r}
age_adj_stats_w_2019 <- age_adj_stats_w_2019 %>%
  mutate(perc_diff_AVG = ((AVG - proj_AVG) / AVG) * 100,
         perc_diff_OBP = ((OBP - proj_OBP) / OBP) * 100,
         perc_diff_SLG = ((SLG - proj_SLG) / SLG) * 100,
         perc_diff_BBRate = ((BBRate - proj_BBRate) / BBRate) * 100,
         perc_diff_SORate = ((SORate - proj_SORate) / SORate) * 100,
         perc_diff_ERA = ((ERA - proj_ERA) / ERA) * 100,
         #perc_diff_wRAA = ((wRAA - proj_wRAA) / wRAA) * 100,
         perc_diff_FIPAdjMinus = ((FIPAdjMinus - proj_FIPAdjMinus) / FIPAdjMinus) *100)
```

```{r}
age_adj_stats_w_2019 <- age_adj_stats_w_2019 %>%
  mutate(total_perc_diff = perc_diff_AVG + perc_diff_OBP + perc_diff_SLG + 
                            perc_diff_BBRate + perc_diff_SORate + perc_diff_ERA + perc_diff_FIPAdjMinus)
```

```{r}
age_adj_stats_w_2019_unique <- age_adj_stats_w_2019 %>%
  distinct(Name, .keep_all = TRUE)
model_performance_2019 <- age_adj_stats_w_2019_unique %>%
  summarise(sum_perc_diff = sum(total_perc_diff)/nrow(age_adj_stats_w_2019_unique))
model_performance_2019
```

```{r}
# Linear regression models
model_avg <- lm(AVG ~ proj_AVG, data = age_adj_stats_w_2019_unique)
model_obp <- lm(OBP ~ proj_OBP, data = age_adj_stats_w_2019_unique)
model_slg <- lm(SLG ~ proj_SLG, data = age_adj_stats_w_2019_unique)

# Summarize models
summary(model_avg)
summary(model_obp)
summary(model_slg)

# Scatter plot with linear regression line for AVG
ggplot(age_adj_stats_w_2019_unique, aes(x = proj_AVG, y = AVG)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Actual vs Projected AVG",
       x = "Projected AVG",
       y = "Actual AVG") +
  theme_minimal()

# Scatter plot with linear regression line for OBP
ggplot(age_adj_stats_w_2019_unique, aes(x = proj_OBP, y = OBP)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Actual vs Projected OBP",
       x = "Projected OBP",
       y = "Actual OBP") +
  theme_minimal()

# Scatter plot with linear regression line for SLG
ggplot(age_adj_stats_w_2019_unique, aes(x = proj_SLG, y = SLG)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Actual vs Projected SLG",
       x = "Projected SLG",
       y = "Actual SLG") +
  theme_minimal()
```



```{r}
# Linear regression models
model_era <- lm(ERA ~ proj_ERA, data = age_adj_stats_w_2019_unique)
model_fip <- lm(FIPAdjMinus ~ proj_FIPAdjMinus, data = age_adj_stats_w_2019_unique)
model_so <- lm(SORate ~ proj_SORate, data = age_adj_stats_w_2019_unique)

# Summarize models
summary(model_era)
summary(model_fip)
summary(model_so)

# Scatter plot with linear regression line for ERA
ggplot(age_adj_stats_w_2019_unique, aes(x = proj_ERA, y = ERA)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Actual vs Projected ERA",
       x = "Projected ERA",
       y = "Actual ERA") +
  theme_minimal()

# Scatter plot with linear regression line for FIPAdjMinus
ggplot(age_adj_stats_w_2019_unique, aes(x = proj_FIPAdjMinus, y = FIPAdjMinus)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Actual vs Projected FIPAdjMinus",
       x = "Projected FIPAdjMinus",
       y = "Actual FIPAdjMinus") +
  theme_minimal()

# Scatter plot with linear regression line for SORate
ggplot(age_adj_stats_w_2019_unique, aes(x = proj_SORate, y = SORate)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Actual vs Projected SORate",
       x = "Projected SORate",
       y = "Actual SORate") +
  theme_minimal()
```


```{r}
model_age_perc_diff <- lm(total_perc_diff ~ Age, data = age_adj_stats_w_2019_unique)

ggplot(age_adj_stats_w_2019_unique, aes(x = Age, y = total_perc_diff)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  labs(title = "Age vs Model Difference",
       x = "Age",
       y = "Model Difference") +
  theme_minimal()
```


